name: Code for Tuscaloosa
description: Code for Tuscaloosa Website
url: http://www.codefortuscaloosa.org
permalink: /blog/:categories/:year/:month/:day/:title.html
exclude: [tools]
gems:
  - jekyll-sitemap
